### ISSUE TITLE
Can't load package

### ISSUE THREAD

**Issue by tsonglew** [tushortz/vscode-Java-Imports#3]
My work tree:

```
.
├── bin
├── libs
│   └── org
│       └── kasheemlew
│           └── kmath
│               └── KDouble.java
└── src
    └── Test.java
```

when I was working on `Test.java`,  the packages in `libs` cannot be loaded

**Comment by tushortz** [comment]
Hi @kasheemlew, sorry this package is just a snippet. It's not meant to read external packages
